### ISSUE TITLE
Release new version after `gexiv2` bump (or lax version specification)

### ISSUE THREAD

**Issue by the-kenny** [felixc/rexiv2#26]
Hello,

Could you create a new release so it's possible to use `rexiv2` with `gexiv2-sys:0.7.0`? Right now the released version of `rexiv2` depends specifically on `gexiv2-sys:0.6.1` and cargo complains when you explicitly add `gexiv2-sys:0.7.0` and `rexiv2` to `Cargo.toml` as they try to link different versions of a native lib:

```
error: native library `gexiv2` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  gexiv2-sys v0.6.1
  gexiv2-sys v0.7.0
```

**Comment by felixc** [comment]
Thanks for the reminder! I'll likely do that this evening.

**Comment by felixc** [comment]
Version 0.4.2 is now on crates.io, and uses gexiv2-sys 0.7!

Thanks for checking out the project and reporting this problem!
